import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  content: {
    paddingHorizontal: 16,
    paddingVertical: 24,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
    textAlign: 'center',
    marginBottom: 32,
  },
  planCardContainer: {
    backgroundColor: 'white',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    position: 'relative',
  },
  planHeaders: {
    flexDirection: 'row',
    marginBottom: 30,
  },
  planTypeCard: {
    flex: 1,
    backgroundColor: '#f8f9fa',
    borderRadius: 4,
    padding: 12,
    marginHorizontal: 2,
    minHeight: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  planTypeCardActive: {
    backgroundColor: '#e8f5e8',
  },
  planTypeText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#2c3e50',
    textAlign: 'center',
  },
  planTypeTextActive: {
    color: '#27ae60',
  },
  planTypeSubText: {
    fontSize: 8,
    color: '#7f8c8d',
    textAlign: 'center',
    marginTop: 2,
  },
  bestBuyBadge: {
    position: 'absolute',
    top: 70,
    right: 20,
    backgroundColor: '#ef4444',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    zIndex: 1,
  },
  bestBuyText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  planOptions: {
    marginBottom: 32,
  },
  planOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginBottom: 12,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  planOptionSelected: {
    backgroundColor: '#fef2f2',
    borderColor: '#ef4444',
  },
  planLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#d1d5db',
    marginRight: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioButtonSelected: {
    borderColor: '#ef4444',
  },
  radioButtonDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#ef4444',
  },
  planDuration: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
  },
  planPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  planBestBuyBadge: {
    position: 'absolute',
    top: -8,
    right: 16,
    backgroundColor: '#ef4444',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    zIndex: 1,
  },
  subscribeButton: {
    backgroundColor: '#ef4444',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 25,
    alignItems: 'center',
  },
  subscribeButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
  },
  gstNote: {
    textAlign: 'center',
    color: '#6b7280',
    fontSize: 16,
    marginBottom: 12,
  },
  couponContainer: {
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 6,
  },
  couponInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
  },
  couponInput: {
    flex: 1,
    marginRight: 8,
    fontSize: 16,
    color: '#1f2937',
  },
  applyButton: {
    paddingHorizontal: 4,
    paddingVertical: 12,
    borderRadius: 8,
  },
  applyButtonText: {
    color: '#3b82f6',
    fontSize: 18,
    fontWeight: '800',
  },
  referal: {
    textAlign: 'right',
    fontSize: 17,
    textDecorationLine: 'underline',
    marginTop: 5,
  },
  referalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    marginTop: 16,
  },
  termsContainer: {
    backgroundColor: 'white',
    padding: 6,
    borderTop: '1px solid #d1d5db',
    borderBottom: '1px solid #d1d5db',
  },
  noteText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#374151',
    marginBottom: 12,
  },
  termsText: {
    fontSize: 16,
    lineHeight: 16,
    marginBottom: 12,
    marginLeft: 20,
    color: '#6b7280',
  },
  callBack: {
    marginTop: 20,
    paddingTop: 16,
    paddingBottom: 16,
    borderTop: '5px solid #000000',
    borderBottom: '5px solid #000000',
    alignItems: 'flex-start',
  },
  callBackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  callBackText: {
    fontSize: 16,
    color: '#374151',
    fontWeight: '500',
    marginRight: 12,
  },
  callBackButton: {
    backgroundColor: '#6b7280',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  callBackButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  emailText: {
    fontSize: 16,
    color: '#374151',
  },
  emailLink: {
    fontSize: 14,
    color: '#3b82f6',
    textDecorationLine: 'underline',
  },
});

export default styles;
